- name: Deploying the APP
  hosts: all
  remote_user: "{{ new_user }}"
  become: yes
  
  vars:
    kube_config_path: "/etc/rancher/k3s/k3s.yaml"
    app_manifest_path: "https://raw.githubusercontent.com/GeorgiYovchev/f-project-test/main/kubernetes/frontend-deploy.yaml"
    local_manifest_path: "/home/{{ new_user }}"
    file_name: "frontend-deploy.yaml"

  tasks:
    - name: Creates ops folder
      ansible.builtin.file:
        path: "{{ local_manifest_path }}/kubernetes"
        state: directory

    - name: Fetch Kubernetes manifest and update image
      ansible.builtin.shell:
        cmd: >
          curl -sL "{{ app_manifest_path }}" |
          sed "s|image:.*|image: {{ image_tag }}|" |
          kubectl apply -f "{{ file_name }}" --kubeconfig "{{ kube_config_path }}"
      
#    - name: Apply Kubernetes manifest
#      ansible.builtin.shell:
#        cmd: "kubectl apply -f {{ local_manifest_path }}/kubernetes/{{ file_name }} --kubeconfig {{ kube_config_path }}"
#