- name: Deploying the APP
  hosts: all
  remote_user: "{{ new_user }}"
  become: yes
  
  vars:
    kube_config_path: "/etc/rancher/k3s/k3s.yaml"
    app_manifest_path: "https://raw.githubusercontent.com/GeorgiYovchev/f-project-test/main/kubernetes/frontend-deploy.yaml"
    local_manifest_path: "/home/{{ new_user }}"
    file_name: "frontend-deploy.yaml"

  tasks:
    - name: Creates ops folder
      ansible.builtin.file:
        path: "{{ local_manifest_path }}/kubernetes"
        state: directory

    - name: Fetch Kubernetes manifest
      ansible.builtin.get_url:
        url: "{{ app_manifest_path }}"
        dest: "{{ local_manifest_path }}/{{ file_name }}"
        force: yes

    - name: Update image in Kubernetes manifest
      ansible.builtin.lineinfile:
        path: "{{ local_manifest_path }}/{{ file_name }}"
        regexp: 'image: georgiyovchev/frontend-service:[^ ]+'
        line: 'image: georgiyovchev/frontend-service:{{ image_tag }}'

    - name: Apply Kubernetes manifest
      ansible.builtin.shell:
        cmd: "kubectl apply -f {{ local_manifest_path }}/{{ file_name }} --kubeconfig {{ kube_config_path }}"


#    - name: Fetch Kubernetes manifest and update image
#      ansible.builtin.shell:
#        cmd: >
#          curl -sL "{{ app_manifest_path }}" |
#          sed "s|georgiyovchev/frontend-service:[^ ]*|georgiyovchev/frontend-service:{{ image_tag | quote }}|" > "{{ local_manifest_path }}/{{ file_name }}" &&
#          kubectl apply -f "{{ local_manifest_path }}/{{ file_name }}" --kubeconfig "{{ kube_config_path }}"