name: CI Pipeline Frontend Service

on:
  push:
   branches:
     - main

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check if editorconfig exists
        if: ${{ hashFiles('.editorconfig') == '' }}
        run: exit 'editorconfig does not exist.'

      - name: Add checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run checker
        run: editorconfig-checker      

  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install black pylint flake8

      - name: Run the linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          pylint: true
          flake8: true

  tests:
    runs-on: ubuntu-latest
    needs: [editorconfig, linters]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        working-directory: ./frontend-service
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Unit Test
        working-directory: ./frontend-service
        run: python -m unittest test_frontend_service.py

  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    needs: [editorconfig, linters, tests]
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-smells:
    name: SonarCloud
    needs: [editorconfig, linters, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
